fun main() {
    println("=== Listas - Inventario de Materiales ===")
    println("Inmutables")
    val materiales = listOf("Acero", "Aluminio", "Cobre", "Plastico", "Caucho")
    println(materiales)
    println("Size: ${materiales.size}")
    println("Primer material: ${materiales[0]}")
    println("Primer elemento: ${materiales.first()}")
    println("Ultimo elemento: ${materiales.last()}")
    println("Elemento indice 2: ${materiales.get(2)}")
    println("Indice de Caucho: ${materiales.indexOf("Caucho")}")
    println("Existe Acero? ${materiales.contains("Acero")}")
    println("Existe Vidrio? ${"Vidrio" in materiales}")

    println("Sublista: ${materiales.subList(1, 4)}")
    println("Tomar 2: ${materiales.take(2)}")
    println("Saltar 3: ${materiales.drop(3)}")
    println("Ultimos 2: ${materiales.takeLast(2)}")

    println("Mutables")
    val maquinas = mutableListOf("Torno", "Fresadora", "Taladro", "Prensa")
    println(maquinas)
    maquinas.add("Cizalla")
    maquinas.add(0, "Robot")
    println(maquinas)
    maquinas.remove("Taladro")
    println(maquinas)
    maquinas[1] = "Torno CNC"
    println(maquinas)

    println("ArrayDeque")
    val pedidos = ArrayDeque<Int>()
    pedidos.addFirst(101)
    println(pedidos)
    pedidos.addFirst(100)
    println(pedidos)
    pedidos.addLast(102)
    println(pedidos)
    pedidos.removeFirst()
    println(pedidos)
    pedidos.removeLast()
    println(pedidos)
}
