fun main() {
    println("=== Set - Codigos de Producto ===")
    println("Inmutables")
    val codigos = setOf(101, 102, 103, 104, 106, 105, 103, 104, 102, 101)
    println(codigos)

    println("Operaciones conjuntas")
    val producidos = setOf(101, 102, 103, 104, 105)
    println("producidos $producidos")
    val defectuosos = setOf(102, 104, 106)
    println("defectuosos $defectuosos")
    println("union ${producidos union defectuosos}")
    println("interseccion ${producidos intersect defectuosos}")
    println("sin defectos ${producidos subtract defectuosos}")

    println("Mutables")
    val categorias = mutableSetOf("Torno", "Fresa", "Prensa")
    println(categorias)
    categorias.add("Torno")
    println(categorias)
    categorias.add("Robot")
    println(categorias)
    categorias.remove("Fresa")
    println(categorias)
    println("Existe Torno? ${"Torno" in categorias}")
    println("Existe Fresa? ${"Fresa" in categorias}")
}
