fun main() {
    println("Set - Codigos de productos")
    println("Inmutables")
    val codigos = setOf(100,200,300,400,500,300,400,200,100,100,300)
    print(codigos)

    println("Operaciones conjutas")
    val producidos = setOf(100,200,300,400)
    println("producidos $producidos")
    val aprobados = setOf(100,300,500,600)
    println("aprobados $aprobados")
    println("union ${producidos union aprobados}")
    println("interseccion ${producidos intersect aprobados}")
    println("substraccion ${producidos subtract aprobados}")
    println("producidos $producidos")
    println("aprobados $aprobados")

    println("Set")
    println("Mutables")
    val proveedores = mutableSetOf("Proveedor A", "Proveedor B", "Proveedor C")
    println(proveedores)
    proveedores.add("Proveedor A")
    println("proveedores")
    proveedores.add("Proveedor D")
    println(proveedores)
    proveedores.remove("Proveedor B")
    println(proveedores)
    println("Verificar si un valor existe ${"Proveedor A" in proveedores}")
    println("Verificar si un valor existe ${"Proveedor B" in proveedores}")
}
