fun main() {
    println("Listas - Inventario de Piezas")
    println("Inmutables")
    val piezas = listOf("Eje", "Buje", "Engranaje", "Tornillo", "Tuerca")
    println(piezas)
    println("Size: ${piezas.size}")
    println("Mostrar el elemento indice 0: ${piezas[0]}")
    println("Mostrar primer elemento: ${piezas.first()}")
    println("Mostrar ultimo elemento: ${piezas.last()}")

    println("Mostrar el elemento indice 2: ${piezas.get(2)}")
    println("Indice de Tornillo: ${piezas.indexOf("Tornillo")}")
    println("Existe Eje? ${piezas.contains("Eje")}")
    println("Existe Arandela? ${"Arandela" in piezas}")

    println("Sublista: ${piezas.subList(1, 4)}")
    println("Tomar primeros dos elementos: ${piezas.take(2)}")
    println("Suprimir 3 primeros elementos: ${piezas.drop(3)}")
    println("Tomar los ultimos dos elementos: ${piezas.takeLast(2)}")
    println(piezas)

    println("Mutables")
    val materiales = mutableListOf("Acero", "Aluminio", "Cobre", "Titanio")
    println(materiales)
    materiales.add("Plastico")
    materiales.add(0, "Hierro")
    println(materiales)
    materiales.remove("Plastico")
    println(materiales)
    materiales[1] = "Acero Inoxidable"
    println(materiales)

    println("Array deque - Cola de produccion")
    val colaProduccion = ArrayDeque<String>()
    println(colaProduccion)
    colaProduccion.addFirst("OP-001")
    println(colaProduccion)
    colaProduccion.addFirst("OP-002")
    println(colaProduccion)
    colaProduccion.addLast("OP-003")
    println(colaProduccion)
    colaProduccion.removeFirst()
    println(colaProduccion)
    colaProduccion.removeLast()
    println(colaProduccion)
}
