fun main() {
    println("Set - Codigos de Producto")
    println("Inmutables")
    val codigos = setOf("PZ-001", "PZ-002", "PZ-003", "PZ-004", "PZ-001", "PZ-002")
    print(codigos)

    println("Operaciones conjuntas")
    val categoriaA = setOf("PZ-001", "PZ-002", "PZ-003")
    println("categoriaA $categoriaA")
    val categoriaB = setOf("PZ-004", "PZ-005", "PZ-006")
    println("categoriaB $categoriaB")
    println("union ${categoriaA union categoriaB}")
    println("interseccion ${categoriaA intersect categoriaB}")
    println("substraccion ${categoriaA subtract categoriaB}")
    println("categoriaA $categoriaA")
    println("categoriaB $categoriaB")

    println("Set Mutables")
    val productos = mutableSetOf("Eje", "Buje", "Engranaje")
    println(productos)
    productos.add("Eje")
    println("productos")
    productos.add("Tornillo")
    println(productos)
    productos.remove("Buje")
    println(productos)
    println("Verificar si un valor existe ${"Eje" in productos}")
    println("Verificar si un valor existe ${"Buje" in productos}")
}
